security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Labor\BackendBundle\Entity\Users: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

 #   providers:
 #       in_memory:
 #           memory:
 #               users:
 #                   user:  { password: userpass, roles: [ 'ROLE_USER' ] }
 #                   admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    providers:
        administrators:
            entity: { class: LaborBackendBundle:Users, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: _security_check
                login_path: login
            logout:
                path:   /logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

#    firewalls:
#        admin_area:
#            pattern:    ^/
#            http_basic: ~
#        login:
#            pattern:  ^/login$
#            security: false

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

#    access_control:
#        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
